### ISSUE TITLE
Links are not visible

### ISSUE THREAD

**Issue by nishantg3soft** [ycecube/phpmaildebug#1]
hi
Thanks for creating this amazing tool. The issue i have found is when email contents any link it doesn't show up in email but when i inspect the source the link is there.
![phpmaildebug 2](https://cloud.githubusercontent.com/assets/11055613/6243087/e8188b48-b760-11e4-9af2-3f8fcea7abb8.png)
![phpmaildebug](https://cloud.githubusercontent.com/assets/11055613/6243088/e81c7e60-b760-11e4-8a1c-5c77914926dd.png)

**Comment by tnagyce** [comment]
Hi!

Currently it does not convert links automatically into clickable links, it is planned to do.

However what you have highlighted doesn't look like a link, it is looks like more like a tag, which won't show up, because the browser can't display it in that way.

Try to change to link to look like &lt;a href="http://..."&gt;Link name&lt;/a&gt; or remove the < and > characters around the link.
